spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: -
            client-secret: -
            scope: profile, email

  datasource:
    url: jdbc:mysql://localhost:3306/music
    username: root
    password: 1234

logging:
  level:
    root: info
    org.springframework.security: debug

cors:
  allow:
    origins: http://localhost:3000
    methods: GET, POST, PUT, DELETE, PATCH, OPTION
