spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(s3G2fjTX8UpUzU0pyV43hyPBnq8LM2f59A2xm1Ne7rrrAlY65OyqFWljlCmNIrP2NfX0Imr7CFL6/R5dU/Rns7/2pvKbRV6iR8WxBxhusJx5anb4olCXwK68i0kitggL)
            client-secret: ENC(p81Kq6PKL87766UmgGokPRvnfnl3Dp54fuytKjpFl2G32VuunC08J1PT2LB+flj+RcUhsgKKgR4=)
            scope: profile, email

  datasource:
    url: jdbc:mysql://localhost:3306/soundflyer
    username: ENC(P4wzO9GTjJwQp7fOh2wzuB2rVwsblwS9dVlps7kFyYU=)
    password: ENC(qhubAFmvwAlxinSmFJ+UMCqaAZVN2azeBV7a1BEaFEo=)

  #pageable
  data:
    web:
      pageable:
        max-page-size: 100
        default-page-size: 10
        
  servlet:
    multipart:
      max-file-size: 6MB
      max-request-size: 6MB

logging:
  level:
    root: info
    org.springframework.security: debug

cors:
  allow:
    origins: http://localhost:3000, https://untitled-a.vercel.app/, https://soundforest.kro.kr/
    methods: GET, POST, PUT, DELETE, PATCH, OPTION


jwt:
  expiration_time: 604800000 #1000*60*60*24*7; 7일
  secret: ENC(AZvoDf/asAWYXziKuttJ5UgS3eQNzC1Kn5NF30mezA3kzJE+JqS0FWsbmOrwNmsqJszBf1kt2o8=)

cookie:
  domain: localhost
  max-age: 604800  # 60*60*24*7, 7일

# swagger
springdoc:
  packages-to-scan: MusicPlatform
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs
  cache:
    disabled: true

# aws
cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: soundflyer
    stack:
      auto: false
    credentials:
      access-key: ENC(Bo04VecppItSjKHcXL+YKbPwf7T9ZqAtTL6n/hWzj1mvl+uvA1T7SQ==)
      secret-key: ENC(u1nVyQgKMfYATTcI1lgcmQT324RGGcLQGGskzYTNkyYH556ZfAB/NqI1WAhtsmN/LbkVc6WFKvgKjki7m5ZXEQ==)

# jasypt
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: ${JASYPT_KEY}

server:
  front: http://localhost:3000
  api: http://localhost:8080
  error-page: http://localhost:3000
  login-page: http://localhost:3000
  # actuator
  tomcat:
    mbeanregistry:
      enabled: true

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
