name: Deploy to Amazon ECS

on:
  push:
    branches: [ "develop" ]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}                     # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: ${{secrets.ECR_REPO}}                     # set this to your Amazon ECR repository name
  ECS_SERVICE: ${{secrets.ECR_SERVICE}}                     # set this to your Amazon ECS service name
  ECS_CLUSTER: ${{secrets.ECR_CLUSTER}}                     # set this to your Amazon ECS cluster name
  ECS_TASK_DEFINITION: .aws/task-definition-template.json   # set this to the path to your Amazon ECS task definition
                                                            # file, e.g. .aws/task-definition.json
  CONTAINER_NAME: ${{secrets.ECR_CONTAINER}}                # set this to the name of the container in the
                                                            # containerDefinitions section of your task definition
  TASK_FAMILY: ${{ secrets.TASK_FAMILY }}
  TASK_ROLE: ${{ secrets.TASK_ROLE }}
  EXECUTION_ROLE: ${{ secrets.EXECUTION_ROLE }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  JASYPT_KEY_NAME: ${{ secrets.JASYPT_KEY_NAME}}
  
permissions:
  id-token: write # OIDC 토큰 사용한 AWS 인증
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
          MYSQL_USER: test
          MYSQL_PASSWORD: test
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -utest -ptest"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v3
      with:
        arguments: clean build
      env:
        JASYPT_KEY: ${{ secrets.JASYPT_KEY }}
        SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/testdb
        SPRING_DATASOURCE_USERNAME: test
        SPRING_DATASOURCE_PASSWORD: test

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}  

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Replace placeholders in Task Definition template
      id: render-task-def
      run: |
        cp $ECS_TASK_DEFINITION task-definition.json
        sed -i "s|<AWS_ACCOUNT_ID>|${AWS_ACCOUNT_ID}|g" task-definition.json
        sed -i "s|<TASK_ROLE>|${TASK_ROLE}|g" task-definition.json
        sed -i "s|<EXECUTION_ROLE>|${EXECUTION_ROLE}|g" task-definition.json
        sed -i "s|<ECR_REPO>|${ECR_REPOSITORY}|g" task-definition.json
        sed -i "s|<TASK_FAMILY>|${TASK_FAMILY}|g" task-definition.json
        sed -i "s|<CONTAINER_NAME>|${CONTAINER_NAME}|g" task-definition.json
        sed -i "s|<TAG>|${GITHUB_SHA}|g" task-definition.json
        sed -i "s|<JASYPT_KEY_NAME>|${JASYPT_KEY_NAME}|g" task-definition.json
        sed -i "s|<AWS_REGION>|${AWS_REGION}|g" task-definition.json

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: ${{ env.CONTAINER_NAME }}
        image: ${{ steps.build-image.outputs.image }}
              
    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true
