name: CI
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:
    inputs:
      type:
        type: choice
        options:
          - Test
          - Deploy

jobs:
  # 모든 경우 실행됨
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Create Cache Docker Image Directory
        run: mkdir -p ~/db-docker-image
        
      - name: Cache DB Docker Image
        id: db-docker-image
        uses: actions/cache@v3
        with:
          path: ~/db-docker-image
          key: db-docker-image-${{ runner.os }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Pull DB Image From ECR
        if: steps.db-docker-image.outputs.cache-hit != 'true'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker pull $ECR_REGISTRY/soundflyer-dev:${{ secrets.DB_TAG }}
          docker save -o \
            ~/db-docker-image/soundflyer-db.tar \
            $ECR_REGISTRY/soundflyer-dev:${{ secrets.DB_TAG }} 
            
      - name: Load Image
        run: |
          docker load -i ~/db-docker-image/soundflyer-db.tar
      
      - name: Check Docker Images 
        run: docker images

      - name: Create Docker Env File
        run: |
          echo '${{ secrets.DOCKER_ENV }}' >> .env
          echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> .env
          
      - name: Create Docker Compose File
        run: |
          echo '${{ secrets.DOCKER_COMPOSE }}' >> docker-compose.yml
          
      - name: Start Containers
        run: docker compose -p soundflyer up -d

      - name: Checkout
        uses: actions/checkout@v4
            
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Gradle Build & Test
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.5
          arguments: build
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'ref/heads/develop' }}
        env:
          JASYPT_KEY: ${{ secrets.JASYPT_KEY }}
      
      # - run: java -Djarmode=layertools -jar build/libs/MusicPlatform-0.0.1-SNAPSHOT.jar extract

      - name: Upload JAR as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-jar
          path: build/libs/MusicPlatform-0.0.1-SNAPSHOT.jar


  # 머지되거나 Deploy로 수동 트리거 되는 경우에 실행
  deploy:
    if: (github.event.pull_request.merged == true || github.event.inputs.type == 'Deploy')
    needs: [ test ]
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: read
      
    steps:
        - name: Download Built JAR
          uses: actions/download-artifact@v4
          with:
            name: built-jar
            path: build/libs

        - name: Configure AWS Credentials
          id: credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-region: ${{ vars.AWS_REGION }}
            role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        
        - name: Upload JAR to S3
          run: |
            aws s3 mv --region ${{ secrets.AWS_REGION }} \
            build/libs/MusicPlatform-0.0.1-SNAPSHOT.jar \
            ${{ secrets.S3_DEV_BACK_LOCATION }}/${GITHUB_SHA::8}.jar
  
        - name: Deploy
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST_DEV }} 
            username: ${{ secrets.SSH_USERNAME_DEV }} 
            port: ${{ secrets.SSH_PORT_DEV }} 
            key: ${{ secrets.SSH_KEY_DEV }} 
            envs: GITHUB_SHA
            script: |
              cd ~/soundflyer-infra/deploy 
              chmod +x ./deploy_back.sh                 
              sudo -E ./deploy_back.sh ${GITHUB_SHA::8} dev 
