name: CICD
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:
    inputs:
      type:
        type: choice
        options:
          - Test
          - Deploy

jobs:
  # 모든 경우 실행됨

  cache-db-image:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    outputs:
      cache-hit: ${{ steps.db-docker-image.outputs.cache-hit }}
      
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4
        
      - name: Checkout Action Module code
        uses: actions/checkout@v4
        with:
          repository: "lcqff/github-actions-module"
          path: ./actions-module

      - name: Create Cache Docker Image Directory
        run: mkdir -p ~/db-docker-image
        
      - name: Cache DB Docker Image
        id: db-docker-image
        uses: actions/cache@v3
        with:
          path: ~/db-docker-image
          key: db-docker-image-${{ runner.os }}

  test:
    needs: [cache-db-image] 
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4
        
      - name: Checkout Action Module code
        uses: actions/checkout@v4
        with:
          repository: "lcqff/github-actions-module"
          path: ./actions-module

      - name: Configure AWS Credentials
        uses: ./actions-module/common/aws
        with:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_ARN }}

      - name: Pull DB Image From ECR
        if: ${{ needs.cache-db-image.outputs.cache-hit == 'false' }}
        uses: ./actions-module/common/container/image-pull
        with:
          REGISTRY: ${{ secrets.ECR_REGISTRY }}
          CACHE_PATH: '~/db-docker-image'
          IMAGE_NAME: 'soundflyer-dev'
          IMAGE_TAG: ${{ secrets.DB_TAG }}
      
      - name: Check Docker Images 
        run: docker images

      - name: Create Docker Env and Docker Compose File
        uses: ./actions-module/common/container/env
        with:
          DOCKER_ENV: "${{ secrets.DOCKER_ENV }}\nECR_REGISTRY=${{ secrets.ECR_REGISTRY }}"
          DOCKER_COMPOSE: ${{ secrets.DOCKER_COMPOSE }}
          
      - name: Start Containers
        run: docker compose -p soundflyer up -d

      - name: Build & Test
        uses: ./actions-module/common/test/gradle
        with:
          JAVA_VERSION: 17
          GRADLE_VERSION: 8.5
          CURRENT_BRANCH:  ${{ github.ref }}
          JASYPT_KEY: ${{ secrets.JASYPT_KEY }}
      
      # - run: java -Djarmode=layertools -jar build/libs/MusicPlatform-0.0.1-SNAPSHOT.jar extract

      - name: Upload JAR as Artifact    
        if: (github.event.pull_request.merged == true || github.event.inputs.type == 'Deploy')
        uses: actions/upload-artifact@v4
        with:
          name: built-jar
          path: build/libs/MusicPlatform-0.0.1-SNAPSHOT.jar


  # 머지되거나 Deploy로 수동 트리거 되는 경우에 실행
  deploy:
    if: (github.event.pull_request.merged == true || github.event.inputs.type == 'Deploy')
    needs: [ test ]
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: read
      
    steps:
        - name: Download Built JAR
          uses: actions/download-artifact@v4
          with:
            name: built-jar
            path: build/libs

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
            aws-region: ${{ secrets.AWS_REGION }}  
        
        - name: Upload JAR to S3
          run: |
            aws s3 mv --region ${{ secrets.AWS_REGION }} \
            build/libs/MusicPlatform-0.0.1-SNAPSHOT.jar \
            ${{ secrets.S3_DEV_BACK_LOCATION }}/${GITHUB_SHA::8}.jar
  
        - name: Deploy
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST_DEV }} 
            username: ${{ secrets.SSH_USERNAME_DEV }} 
            port: ${{ secrets.SSH_PORT_DEV }} 
            key: ${{ secrets.SSH_KEY_DEV }} 
            envs: GITHUB_SHA
            script: |
              cd ~/soundflyer-infra/deploy 
              chmod +x ./deploy_back.sh                 
              sudo -E ./deploy_back.sh ${GITHUB_SHA::8} dev 
